name: Renovate
on:
  workflow_call:
    inputs:
      logLevel:
        description: "Override default log level"
        required: false
        default: "info"
        type: string
      overrideSchedule:
        description: "Override all schedules"
        required: false
        default: "false"
        type: string
concurrency: renovate
jobs:
  verify-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      # Don't waste time starting Renovate if JSON is invalid
      - name: Validate Renovate JSON
        run: jq type .github/renovate.json
  renovate:
      runs-on: ubuntu-latest
      needs:
        - verify-config
      steps:
        - name: Checkout
          uses: actions/checkout@v4.2.2
        - name: Self-hosted Renovate
          uses: renovatebot/github-action@v41.0.3
          env:
            # Repository taken from variable to keep configuration file generic
            RENOVATE_REPOSITORIES: ${{ github.repository }}
            # Onboarding not needed for self hosted
            RENOVATE_ONBOARDING: "false"
            # Override schedule if set
            RENOVATE_FORCE: ${{ github.event.inputs.overrideSchedule == 'true' && '{''schedule'':null}' || '' }}
            LOG_LEVEL: ${{ inputs.logLevel || 'info' }}
          with:
            configurationFile: .github/renovate.json
            token: '${{ secrets.RENOVATE_TOKEN }}'
